{
    "Service": "/MDKLearningApp/Services/ES5.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/MDKLearningApp/Actions/Service/DownloadStartedMessage.action",
    "OnFailure": "/MDKLearningApp/Actions/Service/SyncFailureMessage.action"
}